/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import Fda from './Fda.mp4';
import WingIntro from './WingIntro.mp4';
import WingMobIntro from './WingMobIntro.mp4';

export {Fda, WingIntro, WingMobIntro};
