/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import Dropbox from './Dropbox.png';
import GoogleDrive from './GoogleDrive.png';
import iCloud from './iCloud.png';
import Mega from './Mega.png';
import Transparent from './Transparent.png';
import WingDriveLogo from './WingDriveLogo.svg';

export {Dropbox, GoogleDrive, Mega, Transparent, WingDriveLogo, iCloud};
